$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-types/cspell.schema.json
version: 0.0.4
language: en
words:
  - antd
  - autoincrement
  - callout
  - codepaths
  - cryptjs
  - cuid
  - datasource
  - deepmerge
  - dequal
  - deshake
  - dotenvx
  - ducanh
  - endregion
  - evenodd
  - fieldname
  - Fillin
  - iconfont
  - languagedetector
  - paralleldrive
  - Popconfirm
  - publishs
  - rgba
  - runing
  - SAMESITE
  - signup
  - swiper
  - Swiper
  - tailwindcss
  - tdiary
  - tsbuildinfo
  - turborepo
  - uids
  - vercel
  - wordmark
  - xlink
  - yingyi
  - zuoqiu
  - zustand
ignoreRegExpList: null
flagWords: null
useGitignore: true
ignorePaths:
  - package.json
  - pnpm-lock.yaml
