$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-types/cspell.schema.json

#  Version of the setting file.
version: "0.0.2"

# language - current active spelling language
language: en

# words - list of words to be always considered correct
words:
    - callout
    - evenodd
    - rgba
    - turborepo
    - vercel
    - wordmark
    - xlink

ignoreRegExpList:

# flagWords - list of words to be always considered incorrect
flagWords:

ignorePaths:
    - dist
    - node_modules
    - package.json
    - pnpm-lock.yaml
    - temp
