# REF: https://cspell.org/configuration/

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-types/cspell.schema.json

#  Version of the setting file.
version: "0.0.4"

# language - current active spelling language
language: en

# words - list of words to be always considered correct
words:
    - antd
    - autoincrement
    - callout
    - codepaths
    - cryptjs
    - cuid
    - datasource
    - deepmerge
    - deshake
    - dotenvx
    - endregion
    - evenodd
    - fieldname
    - iconfont
    - languagedetector
    - paralleldrive
    - publishs
    - rgba
    - runing
    - signup
    - tailwindcss
    - tsbuildinfo
    - turborepo
    - uids
    - vercel
    - wordmark
    - xlink
    - yingyi
    - zuoqiu

ignoreRegExpList:

# flagWords - list of words to be always considered incorrect
flagWords:

useGitignore: true

ignorePaths:
    - package.json
    - pnpm-lock.yaml
